language: python
php:
- 3.4

#installation
  #before install

  #install
install:
 - pip install -r requirements.txt

#script
  #before script
  #script
script:
  - python3 test_fruit.py

#after script
  #after success
  #after failure

#deploy
  #before deploy
  #deploy
  #after deploy

#Safe List
branches:
  only:
  - master
  - /[upt][a-q]*[t]\b//

#Blocklist
branches:
  except:
  - opt
#comments

